### ISSUE TITLE
how to train this model

### ISSUE THREAD

**Issue by hajkeoadf** [alastairrr/fall_detector#1]
Hi! I'm quite interested in your work. Now I want to train this model using my own data. Could you offer a training tutorial? Thank you!

**Comment by alastairrr** [comment]
Hi, to train on your own data, you will need to work on the **src/fall_detection/fall_lstm.py** file. Some key variables to adjust include _DATA_PATH_ for the path to the dataset (which needs to contain dir of 'not_fall' and 'fall'), _class_weights_ for class imbalance, and the parameters of the func _modelFit_ and constructor parameters for the class _LSTMFallDetector_. The class is instantiated and run in **src/fall_detection/model_fit.py** for training.
